@startuml coinChange

==case:input:[1,2,5],11==

"node11" -> "node10": amount=11\nres=9223372036854775807\ntarget=10
"node10" -> "node9": amount=10\nres=9223372036854775807\ntarget=9
"node9" -> "node8": amount=9\nres=9223372036854775807\ntarget=8
"node8" -> "node7": amount=8\nres=9223372036854775807\ntarget=7
"node7" -> "node6": amount=7\nres=9223372036854775807\ntarget=6
"node6" -> "node5": amount=6\nres=9223372036854775807\ntarget=5
"node5" -> "node4": amount=5\nres=9223372036854775807\ntarget=4
"node4" -> "node3": amount=4\nres=9223372036854775807\ntarget=3
"node3" -> "node2": amount=3\nres=9223372036854775807\ntarget=2
"node2" -> "node1": amount=2\nres=9223372036854775807\ntarget=1
"node1" -> "node0": amount=1\nres=9223372036854775807\ntarget=0
"node0" -> "node1": amount=1\nres=1\ntarget=0
"node1" -> "node-1": amount=1\nres=1\ntarget=-1
"node-1" -> "node1": amount=1\nres=1\ntarget=-1
"node1" -> "node-4": amount=1\nres=1\ntarget=-4
"node-4" -> "node1": amount=1\nres=1\ntarget=-4
"node1" -> "node2": amount=2\nres=2\ntarget=1
"node2" -> "node0": amount=2\nres=2\ntarget=0
"node0" -> "node2": amount=2\nres=1\ntarget=0
"node2" -> "node-3": amount=2\nres=1\ntarget=-3
"node-3" -> "node2": amount=2\nres=1\ntarget=-3
"node2" -> "node3": amount=3\nres=2\ntarget=2
"node3" -> "node1": amount=3\nres=2\ntarget=1
"node1" -> "node3": amount=3\nres=2\ntarget=1
"node3" -> "node-2": amount=3\nres=2\ntarget=-2
"node-2" -> "node3": amount=3\nres=2\ntarget=-2
"node3" -> "node4": amount=4\nres=3\ntarget=3
"node4" -> "node2": amount=4\nres=3\ntarget=2
"node2" -> "node4": amount=4\nres=2\ntarget=2
"node4" -> "node-1": amount=4\nres=2\ntarget=-1
"node-1" -> "node4": amount=4\nres=2\ntarget=-1
"node4" -> "node5": amount=5\nres=3\ntarget=4
"node5" -> "node3": amount=5\nres=3\ntarget=3
"node3" -> "node5": amount=5\nres=3\ntarget=3
"node5" -> "node0": amount=5\nres=3\ntarget=0
"node0" -> "node5": amount=5\nres=1\ntarget=0
"node5" -> "node6": amount=6\nres=2\ntarget=5
"node6" -> "node4": amount=6\nres=2\ntarget=4
"node4" -> "node6": amount=6\nres=2\ntarget=4
"node6" -> "node1": amount=6\nres=2\ntarget=1
"node1" -> "node6": amount=6\nres=2\ntarget=1
"node6" -> "node7": amount=7\nres=3\ntarget=6
"node7" -> "node5": amount=7\nres=3\ntarget=5
"node5" -> "node7": amount=7\nres=2\ntarget=5
"node7" -> "node2": amount=7\nres=2\ntarget=2
"node2" -> "node7": amount=7\nres=2\ntarget=2
"node7" -> "node8": amount=8\nres=3\ntarget=7
"node8" -> "node6": amount=8\nres=3\ntarget=6
"node6" -> "node8": amount=8\nres=3\ntarget=6
"node8" -> "node3": amount=8\nres=3\ntarget=3
"node3" -> "node8": amount=8\nres=3\ntarget=3
"node8" -> "node9": amount=9\nres=4\ntarget=8
"node9" -> "node7": amount=9\nres=4\ntarget=7
"node7" -> "node9": amount=9\nres=3\ntarget=7
"node9" -> "node4": amount=9\nres=3\ntarget=4
"node4" -> "node9": amount=9\nres=3\ntarget=4
"node9" -> "node10": amount=10\nres=4\ntarget=9
"node10" -> "node8": amount=10\nres=4\ntarget=8
"node8" -> "node10": amount=10\nres=4\ntarget=8
"node10" -> "node5": amount=10\nres=4\ntarget=5
"node5" -> "node10": amount=10\nres=2\ntarget=5
"node10" -> "node11": amount=11\nres=3\ntarget=10
"node11" -> "node9": amount=11\nres=3\ntarget=9
"node9" -> "node11": amount=11\nres=3\ntarget=9
"node11" -> "node6": amount=11\nres=3\ntarget=6
"node6" -> "node11": amount=11\nres=3\ntarget=6
@enduml